jwt:
    secret: ${DB_SECRET}
    access:
        expiration: 900000
    refresh:
        expiration: 86400000
management:
    endpoints:
        web:
            exposure:
                include: "*"
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        url: jdbc:postgresql://localhost:5432/postgres-jat-db
    flyway:
        enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        show-sql: true
    config:
        import: env.properties
app:
    cookie:
        secure: false
#    mail:
#        host: smtp.gmail.com
#        port: 587
#        username: ${MAIL_ADDRESS}
#        password: ${MAIL_PASSWORD}
#        properties:
#            mail:
#                smtp:
#                    auth: true
#                    starttls:
#                        enable: true