CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE users (
    id       BIGINT       NOT NULL,
    username VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    type     VARCHAR(255),
    enabled  BOOLEAN      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_type CHECK (type IN ('USER', 'ADMIN'))
);

CREATE TABLE jobs (
    id             BIGINT         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    company        VARCHAR(255)   NOT NULL,
    location       VARCHAR(255)   NOT NULL,
    salary_lowest  NUMERIC(10, 2),
    salary_highest NUMERIC(10, 2),
    created_at     DATE,
    closing_at     DATE,
    status         VARCHAR(255),
    contract       VARCHAR(255)   NOT NULL,
    position       VARCHAR(255)   NOT NULL,
    notes          VARCHAR(255),
    archived       BOOLEAN        NOT NULL,
    url            VARCHAR(255),
    user_id        BIGINT         NOT NULL,
    CONSTRAINT pk_jobs PRIMARY KEY (id),
    CONSTRAINT fk_jobs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_jobs_status CHECK (status IN ('PENDING', 'SCREENING', 'INTERVIEW', 'OFFER', 'GHOSTED', 'REJECTED')),
    CONSTRAINT chk_jobs_contract CHECK (contract IN ('B2B', 'UOP', 'UOZ', 'UOD', 'INTERN')),
    CONSTRAINT chk_jobs_position CHECK (position IN ('INTERN', 'JUNIOR', 'MID', 'SENIOR'))
);

CREATE INDEX idx_jobs_user_id ON jobs (user_id);

CREATE TABLE refresh_tokens (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT,
    token       VARCHAR(255) NOT NULL,
    expiry_date TIMESTAMP    NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_refresh_tokens_token UNIQUE (token),
    CONSTRAINT uk_refresh_tokens_user UNIQUE (user_id)
);

CREATE TABLE otp_tokens (
    id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    otp        VARCHAR(255),
    email      VARCHAR(255),
    used       BOOLEAN      NOT NULL,
    created_at TIMESTAMP,
    expires_at TIMESTAMP,
    CONSTRAINT pk_otp_tokens PRIMARY KEY (id)
);
